name: Checkin

on:
  workflow_dispatch:
  schedule:
    - cron: 0 2,14 * * *

env:
  IKUUU_USERNAME: ${{ secrets.IKUUU_USERNAME }}
  IKUUU_PASSWORD: ${{ secrets.IKUUU_PASSWORD }}
#   ZIP_PASSWD: ${{ secrets.ZIP_PASSWD }}

jobs:
  ikuuu:
    runs-on: ubuntu-latest
#     container:
#       image: mcr.microsoft.com/playwright

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - uses: actions/setup-node@main

    - uses: microsoft/playwright-github-action@main

    - name: Install dependencies and run tests
      run: cd ikuuu && npm install && node checkin.js
      
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 6

#     - name: Extract Profile
#       run: unzip -P "${{ env.ZIP_PASSWD }}" profile.zip

#     - name: Checkin
#       run: sh checkin.sh checkin oshwhub.com
